package org.arn.hdsscapture.repository;

import java.util.List;

import org.arn.hdsscapture.entity.Sociodemographic;
import org.arn.hdsscapture.entity.Vaccination;
import org.arn.hdsscapture.views.IndividualSearch;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

public interface SesRepository extends JpaRepository <Sociodemographic, String> {
	
	@Query(nativeQuery = true, value = "SELECT a.* FROM sociodemographic a INNER JOIN residency b ON a.socialgroup_uuid = b.socialgroup_uuid "
	        + " WHERE b.endType = 1 AND a.insertDate >= (SELECT r.sesDate from settings r) GROUP BY a.socialgroup_uuid LIMIT ?1 OFFSET ?2")
	List<Sociodemographic> findSes(int pageSize, int offset);
	
	@Query(nativeQuery = true, value = "SELECT a.* FROM sociodemographic a WHERE a.`status`=2 AND a.formcompldate > (SELECT r.startDate from round r ORDER BY r.roundNumber DESC limit 1)")
    List<Sociodemographic> rejected();
	
	@Query(nativeQuery = true, value = "SELECT * FROM sociodemographic WHERE uuid = :uuid LIMIT 1")
    List<Sociodemographic> findByUuids(@Param("uuid") String uuid);
	
	@Query(nativeQuery = true, value ="SELECT b.extId as socialgroup_uuid,aircon_fcorres,aircon_num_fcorres,animal_othr_fcorres,animal_othr_num_fcorres,\r\n"
			+ "animal_othr_spfy_fcorres,bike_fcorres,bike_num_fcorres,blender_fcorres,\r\n"
			+ "blender_num_fcorres,boat_fcorres,boat_num_fcorres,cabinets_fcorres,\r\n"
			+ "cabinets_num_fcorres,car_fcorres,car_num_fcorres,cart_fcorres,\r\n"
			+ "cart_num_fcorres,cattle_fcorres,cattle_num_fcorres,cethnic,\r\n"
			+ "chew_bnut_oecoccur,chew_oecoccur,computer_fcorres,computer_num_fcorres,\r\n"
			+ "cooking_inside_fcorres,cooking_loc_fcorres,cooking_room_fcorres,cooking_vent_fcorres,\r\n"
			+ "donkey_fcorres,donkey_num_fcorres,drink_oecoccur,dvd_cd_fcorres,\r\n"
			+ "dvd_cd_num_fcorres,a.edtime,electricity_fcorres,ext_wall_fcorres,ext_wall_spfy_fcorres,\r\n"
			+ "floor_fcorres,floor_spfy_fcorres,foam_matt_fcorres,foam_matt_num_fcorres,\r\n"
			+ "form_comments_txt,form_comments_yn,formcompldate,fridge_fcorres,fridge_num_fcorres,\r\n"
			+ "concat(f.firstName,' ',f.lastName) as fw_uuid,goat_fcorres,goat_num_fcorres,\r\n"
			+ "h2o_dist_fcorres,h2o_fcorres,h2o_hours_fcorres,\r\n"
			+ "h2o_mins_fcorres,h2o_prep_fcorres,h2o_prep_spfy_fcorres_1,\r\n"
			+ "h2o_prep_spfy_fcorres_2,h2o_prep_spfy_fcorres_3,\r\n"
			+ "h2o_prep_spfy_fcorres_4,h2o_prep_spfy_fcorres_5,h2o_spfy_fcorres,\r\n"
			+ "head_hh_fcorres,head_hh_spfy_fcorres,horse_fcorres,\r\n"
			+ "horse_num_fcorres,house_occ_ge5_fcorres,house_occ_lt5_fcorres,\r\n"
			+ "house_occ_tot_fcorres,house_room_child_fcorres,\r\n"
			+ "house_rooms_fcorres,a.individual_uuid,a.insertDate,\r\n"
			+ "internet_fcorres,job_busown_spfy_scorres,job_othr_spfy_scorres,\r\n"
			+ "job_salary_spfy_scorres,job_scorres,job_skilled_spfy_scorres,\r\n"
			+ "job_smbus_spfy_scorres,job_unskilled_spfy_scorres,land_fcorres,\r\n"
			+ "land_use_fcorres_1,land_use_fcorres_2,land_use_fcorres_3,\r\n"
			+ "land_use_fcorres_4,land_use_fcorres_5,land_use_fcorres_88,\r\n"
			+ "land_use_spfy_fcorres_88,landline_fcorres,lantern_fcorres,\r\n"
			+ "lantern_num_fcorres,livestock_fcorres,c.compno as location_uuid,\r\n"
			+ "marital_age,marital_scorres,\r\n"
			+ "mobile_access_fcorres,mobile_fcorres,mobile_num_fcorres,\r\n"
			+ "mosquito_net_fcorres,mosquito_net_num_fcorres,motorcycle_fcorres,\r\n"
			+ "motorcycle_num_fcorres,nth_trb_spfy_cethnic,\r\n"
			+ "othr_trb_spfy_cethnic,own_rent_scorres,own_rent_spfy_scorres,\r\n"
			+ "pig_fcorres,pig_num_fcorres,plough_fcorres,\r\n"
			+ "plough_num_fcorres,poultry_fcorres,poultry_num_fcorres,\r\n"
			+ "ptr_busown_spfy_scorres,ptr_othr_spfy_scorres,\r\n"
			+ "ptr_salary_spfy_scorres,ptr_scorres,ptr_skilled_spfy_scorres,\r\n"
			+ "ptr_smbus_spfy_scorres,ptr_unskilled_spfy_scorres,radio_fcorres,\r\n"
			+ "radio_num_fcorres,religion_scorres,religion_spfy_scorres,\r\n"
			+ "roof_fcorres,roof_spfy_fcorres,sat_dish_fcorres,\r\n"
			+ "sat_dish_num_fcorres,sd_obsstdat,sew_fcorres,\r\n"
			+ "sew_num_fcorres,sheep_fcorres,sheep_num_fcorres,\r\n"
			+ "smoke_hhold_in_oecdosfrq,smoke_hhold_oecoccur,smoke_in_oecdosfrq,\r\n"
			+ "smoke_oecoccur,sofa_fcorres,sofa_num_fcorres,\r\n"
			+ "solar_fcorres,spring_matt_fcorres,spring_matt_num_fcorres,\r\n"
			+ "stove_fcorres,stove_fuel_fcorres_1,stove_fuel_fcorres_10,\r\n"
			+ "stove_fuel_fcorres_11,stove_fuel_fcorres_12,\r\n"
			+ "stove_fuel_fcorres_13,stove_fuel_fcorres_14,stove_fuel_fcorres_2,\r\n"
			+ "stove_fuel_fcorres_3,stove_fuel_fcorres_4,stove_fuel_fcorres_5,\r\n"
			+ "stove_fuel_fcorres_6,stove_fuel_fcorres_7,stove_fuel_fcorres_8,\r\n"
			+ "stove_fuel_fcorres_88,stove_fuel_fcorres_9,\r\n"
			+ "stove_fuel_spfy_fcorres_88,stove_spfy_fcorres,straw_matt_fcorres,a.sttime,\r\n"
			+ "straw_matt_num_fcorres,tables_fcorres,tables_num_fcorres,\r\n"
			+ "toilet_fcorres,toilet_loc_fcorres,toilet_loc_spfy_fcorres,\r\n"
			+ "toilet_share_fcorres,toilet_share_num_fcorres,\r\n"
			+ "toilet_spfy_fcorres,tractor_fcorres,tractor_num_fcorres,\r\n"
			+ "tricycles_fcorres,tricycles_num_fcorres,tv_fcorres,\r\n"
			+ "tv_num_fcorres,a.uuid,wash_fcorres,wash_num_fcorres,comment,a.status,supervisor,approveDate,\r\n"
			+ "watch_fcorres,watch_num_fcorres from sociodemographic a INNER JOIN socialgroup b ON a.socialgroup_uuid=b.uuid \r\n"
			+ "INNER JOIN location c on a.location_uuid=c.uuid \r\n"
			+ "INNER JOIN fieldworker f on a.fw_uuid=f.fw_uuid \r\n"
			+ "where a.formcompldate > (SELECT r.startDate from round r ORDER BY r.roundNumber DESC limit 1) AND a.uuid = :uuid LIMIT 1")
	List<Sociodemographic> findByUuid(@Param("uuid") String uuid);
	
	@Query(nativeQuery = true, value ="SELECT b.extId as socialgroup_uuid,aircon_fcorres,aircon_num_fcorres,animal_othr_fcorres,animal_othr_num_fcorres,\r\n"
			+ "animal_othr_spfy_fcorres,bike_fcorres,bike_num_fcorres,blender_fcorres,\r\n"
			+ "blender_num_fcorres,boat_fcorres,boat_num_fcorres,cabinets_fcorres,\r\n"
			+ "cabinets_num_fcorres,car_fcorres,car_num_fcorres,cart_fcorres,\r\n"
			+ "cart_num_fcorres,cattle_fcorres,cattle_num_fcorres,cethnic,\r\n"
			+ "chew_bnut_oecoccur,chew_oecoccur,computer_fcorres,computer_num_fcorres,\r\n"
			+ "cooking_inside_fcorres,cooking_loc_fcorres,cooking_room_fcorres,cooking_vent_fcorres,\r\n"
			+ "donkey_fcorres,donkey_num_fcorres,drink_oecoccur,dvd_cd_fcorres,\r\n"
			+ "dvd_cd_num_fcorres,a.edtime,electricity_fcorres,ext_wall_fcorres,ext_wall_spfy_fcorres,\r\n"
			+ "floor_fcorres,floor_spfy_fcorres,foam_matt_fcorres,foam_matt_num_fcorres,\r\n"
			+ "form_comments_txt,form_comments_yn,formcompldate,fridge_fcorres,fridge_num_fcorres,\r\n"
			+ "concat(f.firstName,' ',f.lastName) as fw_uuid,goat_fcorres,goat_num_fcorres,\r\n"
			+ "h2o_dist_fcorres,h2o_fcorres,h2o_hours_fcorres,\r\n"
			+ "h2o_mins_fcorres,h2o_prep_fcorres,h2o_prep_spfy_fcorres_1,\r\n"
			+ "h2o_prep_spfy_fcorres_2,h2o_prep_spfy_fcorres_3,\r\n"
			+ "h2o_prep_spfy_fcorres_4,h2o_prep_spfy_fcorres_5,h2o_spfy_fcorres,\r\n"
			+ "head_hh_fcorres,head_hh_spfy_fcorres,horse_fcorres,\r\n"
			+ "horse_num_fcorres,house_occ_ge5_fcorres,house_occ_lt5_fcorres,\r\n"
			+ "house_occ_tot_fcorres,house_room_child_fcorres,\r\n"
			+ "house_rooms_fcorres,groupName as individual_uuid,a.insertDate,\r\n"
			+ "internet_fcorres,job_busown_spfy_scorres,job_othr_spfy_scorres,\r\n"
			+ "job_salary_spfy_scorres,job_scorres,job_skilled_spfy_scorres,\r\n"
			+ "job_smbus_spfy_scorres,job_unskilled_spfy_scorres,land_fcorres,\r\n"
			+ "land_use_fcorres_1,land_use_fcorres_2,land_use_fcorres_3,\r\n"
			+ "land_use_fcorres_4,land_use_fcorres_5,land_use_fcorres_88,\r\n"
			+ "land_use_spfy_fcorres_88,landline_fcorres,lantern_fcorres,\r\n"
			+ "lantern_num_fcorres,livestock_fcorres,c.compno as location_uuid,\r\n"
			+ "marital_age,marital_scorres,\r\n"
			+ "mobile_access_fcorres,mobile_fcorres,mobile_num_fcorres,\r\n"
			+ "mosquito_net_fcorres,mosquito_net_num_fcorres,motorcycle_fcorres,\r\n"
			+ "motorcycle_num_fcorres,nth_trb_spfy_cethnic,\r\n"
			+ "othr_trb_spfy_cethnic,own_rent_scorres,own_rent_spfy_scorres,\r\n"
			+ "pig_fcorres,pig_num_fcorres,plough_fcorres,\r\n"
			+ "plough_num_fcorres,poultry_fcorres,poultry_num_fcorres,\r\n"
			+ "ptr_busown_spfy_scorres,ptr_othr_spfy_scorres,\r\n"
			+ "ptr_salary_spfy_scorres,ptr_scorres,ptr_skilled_spfy_scorres,\r\n"
			+ "ptr_smbus_spfy_scorres,ptr_unskilled_spfy_scorres,radio_fcorres,\r\n"
			+ "radio_num_fcorres,religion_scorres,religion_spfy_scorres,\r\n"
			+ "roof_fcorres,roof_spfy_fcorres,sat_dish_fcorres,\r\n"
			+ "sat_dish_num_fcorres,sd_obsstdat,sew_fcorres,\r\n"
			+ "sew_num_fcorres,sheep_fcorres,sheep_num_fcorres,\r\n"
			+ "smoke_hhold_in_oecdosfrq,smoke_hhold_oecoccur,smoke_in_oecdosfrq,\r\n"
			+ "smoke_oecoccur,sofa_fcorres,sofa_num_fcorres,\r\n"
			+ "solar_fcorres,spring_matt_fcorres,spring_matt_num_fcorres,\r\n"
			+ "stove_fcorres,stove_fuel_fcorres_1,stove_fuel_fcorres_10,\r\n"
			+ "stove_fuel_fcorres_11,stove_fuel_fcorres_12,\r\n"
			+ "stove_fuel_fcorres_13,stove_fuel_fcorres_14,stove_fuel_fcorres_2,\r\n"
			+ "stove_fuel_fcorres_3,stove_fuel_fcorres_4,stove_fuel_fcorres_5,\r\n"
			+ "stove_fuel_fcorres_6,stove_fuel_fcorres_7,stove_fuel_fcorres_8,\r\n"
			+ "stove_fuel_fcorres_88,stove_fuel_fcorres_9,\r\n"
			+ "stove_fuel_spfy_fcorres_88,stove_spfy_fcorres,straw_matt_fcorres,a.sttime,\r\n"
			+ "straw_matt_num_fcorres,tables_fcorres,tables_num_fcorres,\r\n"
			+ "toilet_fcorres,toilet_loc_fcorres,toilet_loc_spfy_fcorres,\r\n"
			+ "toilet_share_fcorres,toilet_share_num_fcorres,\r\n"
			+ "toilet_spfy_fcorres,tractor_fcorres,tractor_num_fcorres,\r\n"
			+ "tricycles_fcorres,tricycles_num_fcorres,tv_fcorres,\r\n"
			+ "tv_num_fcorres,a.uuid,wash_fcorres,wash_num_fcorres,comment,a.status,supervisor,approveDate,\r\n"
			+ "watch_fcorres,watch_num_fcorres from sociodemographic a INNER JOIN socialgroup b ON a.socialgroup_uuid=b.uuid \r\n"
			+ "INNER JOIN location c on a.location_uuid=c.uuid \r\n"
			+ "INNER JOIN fieldworker f on a.fw_uuid=f.fw_uuid \r\n"
			+ "where a.fw_uuid= :fw AND a.formcompldate > (SELECT r.startDate from round r ORDER BY r.roundNumber DESC limit 1)")
	List<Sociodemographic> findItem(@Param("fw") String fw);
	
	@Query(nativeQuery = true, value ="SELECT b.extId as socialgroup_uuid,aircon_fcorres,aircon_num_fcorres,animal_othr_fcorres,animal_othr_num_fcorres,\r\n"
			+ "animal_othr_spfy_fcorres,bike_fcorres,bike_num_fcorres,blender_fcorres,\r\n"
			+ "blender_num_fcorres,boat_fcorres,boat_num_fcorres,cabinets_fcorres,\r\n"
			+ "cabinets_num_fcorres,car_fcorres,car_num_fcorres,cart_fcorres,\r\n"
			+ "cart_num_fcorres,cattle_fcorres,cattle_num_fcorres,cethnic,\r\n"
			+ "chew_bnut_oecoccur,chew_oecoccur,computer_fcorres,computer_num_fcorres,\r\n"
			+ "cooking_inside_fcorres,cooking_loc_fcorres,cooking_room_fcorres,cooking_vent_fcorres,\r\n"
			+ "donkey_fcorres,donkey_num_fcorres,drink_oecoccur,dvd_cd_fcorres,\r\n"
			+ "dvd_cd_num_fcorres,a.edtime,electricity_fcorres,ext_wall_fcorres,ext_wall_spfy_fcorres,\r\n"
			+ "floor_fcorres,floor_spfy_fcorres,foam_matt_fcorres,foam_matt_num_fcorres,\r\n"
			+ "form_comments_txt,form_comments_yn,formcompldate,fridge_fcorres,fridge_num_fcorres,\r\n"
			+ "concat(f.firstName,' ',f.lastName) as fw_uuid,goat_fcorres,goat_num_fcorres,\r\n"
			+ "h2o_dist_fcorres,h2o_fcorres,h2o_hours_fcorres,\r\n"
			+ "h2o_mins_fcorres,h2o_prep_fcorres,h2o_prep_spfy_fcorres_1,\r\n"
			+ "h2o_prep_spfy_fcorres_2,h2o_prep_spfy_fcorres_3,\r\n"
			+ "h2o_prep_spfy_fcorres_4,h2o_prep_spfy_fcorres_5,h2o_spfy_fcorres,\r\n"
			+ "head_hh_fcorres,head_hh_spfy_fcorres,horse_fcorres,\r\n"
			+ "horse_num_fcorres,house_occ_ge5_fcorres,house_occ_lt5_fcorres,\r\n"
			+ "house_occ_tot_fcorres,house_room_child_fcorres,\r\n"
			+ "house_rooms_fcorres,groupName as individual_uuid,a.insertDate,\r\n"
			+ "internet_fcorres,job_busown_spfy_scorres,job_othr_spfy_scorres,\r\n"
			+ "job_salary_spfy_scorres,job_scorres,job_skilled_spfy_scorres,\r\n"
			+ "job_smbus_spfy_scorres,job_unskilled_spfy_scorres,land_fcorres,\r\n"
			+ "land_use_fcorres_1,land_use_fcorres_2,land_use_fcorres_3,\r\n"
			+ "land_use_fcorres_4,land_use_fcorres_5,land_use_fcorres_88,\r\n"
			+ "land_use_spfy_fcorres_88,landline_fcorres,lantern_fcorres,\r\n"
			+ "lantern_num_fcorres,livestock_fcorres,c.compno as location_uuid,\r\n"
			+ "marital_age,marital_scorres,\r\n"
			+ "mobile_access_fcorres,mobile_fcorres,mobile_num_fcorres,\r\n"
			+ "mosquito_net_fcorres,mosquito_net_num_fcorres,motorcycle_fcorres,\r\n"
			+ "motorcycle_num_fcorres,nth_trb_spfy_cethnic,\r\n"
			+ "othr_trb_spfy_cethnic,own_rent_scorres,own_rent_spfy_scorres,\r\n"
			+ "pig_fcorres,pig_num_fcorres,plough_fcorres,\r\n"
			+ "plough_num_fcorres,poultry_fcorres,poultry_num_fcorres,\r\n"
			+ "ptr_busown_spfy_scorres,ptr_othr_spfy_scorres,\r\n"
			+ "ptr_salary_spfy_scorres,ptr_scorres,ptr_skilled_spfy_scorres,\r\n"
			+ "ptr_smbus_spfy_scorres,ptr_unskilled_spfy_scorres,radio_fcorres,\r\n"
			+ "radio_num_fcorres,religion_scorres,religion_spfy_scorres,\r\n"
			+ "roof_fcorres,roof_spfy_fcorres,sat_dish_fcorres,\r\n"
			+ "sat_dish_num_fcorres,sd_obsstdat,sew_fcorres,\r\n"
			+ "sew_num_fcorres,sheep_fcorres,sheep_num_fcorres,\r\n"
			+ "smoke_hhold_in_oecdosfrq,smoke_hhold_oecoccur,smoke_in_oecdosfrq,\r\n"
			+ "smoke_oecoccur,sofa_fcorres,sofa_num_fcorres,\r\n"
			+ "solar_fcorres,spring_matt_fcorres,spring_matt_num_fcorres,\r\n"
			+ "stove_fcorres,stove_fuel_fcorres_1,stove_fuel_fcorres_10,\r\n"
			+ "stove_fuel_fcorres_11,stove_fuel_fcorres_12,\r\n"
			+ "stove_fuel_fcorres_13,stove_fuel_fcorres_14,stove_fuel_fcorres_2,\r\n"
			+ "stove_fuel_fcorres_3,stove_fuel_fcorres_4,stove_fuel_fcorres_5,\r\n"
			+ "stove_fuel_fcorres_6,stove_fuel_fcorres_7,stove_fuel_fcorres_8,\r\n"
			+ "stove_fuel_fcorres_88,stove_fuel_fcorres_9,\r\n"
			+ "stove_fuel_spfy_fcorres_88,stove_spfy_fcorres,straw_matt_fcorres,a.sttime,\r\n"
			+ "straw_matt_num_fcorres,tables_fcorres,tables_num_fcorres,\r\n"
			+ "toilet_fcorres,toilet_loc_fcorres,toilet_loc_spfy_fcorres,\r\n"
			+ "toilet_share_fcorres,toilet_share_num_fcorres,\r\n"
			+ "toilet_spfy_fcorres,tractor_fcorres,tractor_num_fcorres,\r\n"
			+ "tricycles_fcorres,tricycles_num_fcorres,tv_fcorres,\r\n"
			+ "tv_num_fcorres,a.uuid,wash_fcorres,wash_num_fcorres,comment,a.status,supervisor,approveDate,\r\n"
			+ "watch_fcorres,watch_num_fcorres from sociodemographic a INNER JOIN socialgroup b ON a.socialgroup_uuid=b.uuid \r\n"
			+ "INNER JOIN location c on a.location_uuid=c.uuid \r\n"
			+ "INNER JOIN fieldworker f on a.fw_uuid=f.fw_uuid \r\n"
			+ "where a.`status`=3 AND a.formcompldate > (SELECT r.startDate from round r ORDER BY r.roundNumber DESC limit 1)")
	List<Sociodemographic> findItems();

	
	@Query(nativeQuery = true, value ="SELECT b.extId as socialgroup_uuid,aircon_fcorres,aircon_num_fcorres,animal_othr_fcorres,animal_othr_num_fcorres,\r\n"
			+ "animal_othr_spfy_fcorres,bike_fcorres,bike_num_fcorres,blender_fcorres,\r\n"
			+ "blender_num_fcorres,boat_fcorres,boat_num_fcorres,cabinets_fcorres,\r\n"
			+ "cabinets_num_fcorres,car_fcorres,car_num_fcorres,cart_fcorres,\r\n"
			+ "cart_num_fcorres,cattle_fcorres,cattle_num_fcorres,cethnic,\r\n"
			+ "chew_bnut_oecoccur,chew_oecoccur,computer_fcorres,computer_num_fcorres,\r\n"
			+ "cooking_inside_fcorres,cooking_loc_fcorres,cooking_room_fcorres,cooking_vent_fcorres,\r\n"
			+ "donkey_fcorres,donkey_num_fcorres,drink_oecoccur,dvd_cd_fcorres,\r\n"
			+ "dvd_cd_num_fcorres,a.edtime,electricity_fcorres,ext_wall_fcorres,ext_wall_spfy_fcorres,\r\n"
			+ "floor_fcorres,floor_spfy_fcorres,foam_matt_fcorres,foam_matt_num_fcorres,\r\n"
			+ "form_comments_txt,form_comments_yn,formcompldate,fridge_fcorres,fridge_num_fcorres,\r\n"
			+ "concat(f.firstName,' ',f.lastName) as fw_uuid,goat_fcorres,goat_num_fcorres,\r\n"
			+ "h2o_dist_fcorres,h2o_fcorres,h2o_hours_fcorres,\r\n"
			+ "h2o_mins_fcorres,h2o_prep_fcorres,h2o_prep_spfy_fcorres_1,\r\n"
			+ "h2o_prep_spfy_fcorres_2,h2o_prep_spfy_fcorres_3,\r\n"
			+ "h2o_prep_spfy_fcorres_4,h2o_prep_spfy_fcorres_5,h2o_spfy_fcorres,\r\n"
			+ "head_hh_fcorres,head_hh_spfy_fcorres,horse_fcorres,\r\n"
			+ "horse_num_fcorres,house_occ_ge5_fcorres,house_occ_lt5_fcorres,\r\n"
			+ "house_occ_tot_fcorres,house_room_child_fcorres,\r\n"
			+ "house_rooms_fcorres,groupName as individual_uuid,a.insertDate,\r\n"
			+ "internet_fcorres,job_busown_spfy_scorres,job_othr_spfy_scorres,\r\n"
			+ "job_salary_spfy_scorres,job_scorres,job_skilled_spfy_scorres,\r\n"
			+ "job_smbus_spfy_scorres,job_unskilled_spfy_scorres,land_fcorres,\r\n"
			+ "land_use_fcorres_1,land_use_fcorres_2,land_use_fcorres_3,\r\n"
			+ "land_use_fcorres_4,land_use_fcorres_5,land_use_fcorres_88,\r\n"
			+ "land_use_spfy_fcorres_88,landline_fcorres,lantern_fcorres,\r\n"
			+ "lantern_num_fcorres,livestock_fcorres,c.compno as location_uuid,\r\n"
			+ "marital_age,marital_scorres,\r\n"
			+ "mobile_access_fcorres,mobile_fcorres,mobile_num_fcorres,\r\n"
			+ "mosquito_net_fcorres,mosquito_net_num_fcorres,motorcycle_fcorres,\r\n"
			+ "motorcycle_num_fcorres,nth_trb_spfy_cethnic,\r\n"
			+ "othr_trb_spfy_cethnic,own_rent_scorres,own_rent_spfy_scorres,\r\n"
			+ "pig_fcorres,pig_num_fcorres,plough_fcorres,\r\n"
			+ "plough_num_fcorres,poultry_fcorres,poultry_num_fcorres,\r\n"
			+ "ptr_busown_spfy_scorres,ptr_othr_spfy_scorres,\r\n"
			+ "ptr_salary_spfy_scorres,ptr_scorres,ptr_skilled_spfy_scorres,\r\n"
			+ "ptr_smbus_spfy_scorres,ptr_unskilled_spfy_scorres,radio_fcorres,\r\n"
			+ "radio_num_fcorres,religion_scorres,religion_spfy_scorres,\r\n"
			+ "roof_fcorres,roof_spfy_fcorres,sat_dish_fcorres,\r\n"
			+ "sat_dish_num_fcorres,sd_obsstdat,sew_fcorres,\r\n"
			+ "sew_num_fcorres,sheep_fcorres,sheep_num_fcorres,\r\n"
			+ "smoke_hhold_in_oecdosfrq,smoke_hhold_oecoccur,smoke_in_oecdosfrq,\r\n"
			+ "smoke_oecoccur,sofa_fcorres,sofa_num_fcorres,\r\n"
			+ "solar_fcorres,spring_matt_fcorres,spring_matt_num_fcorres,\r\n"
			+ "stove_fcorres,stove_fuel_fcorres_1,stove_fuel_fcorres_10,\r\n"
			+ "stove_fuel_fcorres_11,stove_fuel_fcorres_12,\r\n"
			+ "stove_fuel_fcorres_13,stove_fuel_fcorres_14,stove_fuel_fcorres_2,\r\n"
			+ "stove_fuel_fcorres_3,stove_fuel_fcorres_4,stove_fuel_fcorres_5,\r\n"
			+ "stove_fuel_fcorres_6,stove_fuel_fcorres_7,stove_fuel_fcorres_8,\r\n"
			+ "stove_fuel_fcorres_88,stove_fuel_fcorres_9,\r\n"
			+ "stove_fuel_spfy_fcorres_88,stove_spfy_fcorres,straw_matt_fcorres,a.sttime,\r\n"
			+ "straw_matt_num_fcorres,tables_fcorres,tables_num_fcorres,\r\n"
			+ "toilet_fcorres,toilet_loc_fcorres,toilet_loc_spfy_fcorres,\r\n"
			+ "toilet_share_fcorres,toilet_share_num_fcorres,\r\n"
			+ "toilet_spfy_fcorres,tractor_fcorres,tractor_num_fcorres,\r\n"
			+ "tricycles_fcorres,tricycles_num_fcorres,tv_fcorres,\r\n"
			+ "tv_num_fcorres,a.uuid,wash_fcorres,wash_num_fcorres,comment,a.status,supervisor,approveDate,\r\n"
			+ "watch_fcorres,watch_num_fcorres from sociodemographic a INNER JOIN socialgroup b ON a.socialgroup_uuid=b.uuid \r\n"
			+ "INNER JOIN location c on a.location_uuid=c.uuid \r\n"
			+ "INNER JOIN fieldworker f on a.fw_uuid=f.fw_uuid \r\n"
			+ "where a.`status`=2 AND a.formcompldate > (SELECT r.startDate from round r ORDER BY r.roundNumber DESC limit 1)")
	List<Sociodemographic> findRej();

}
