INSERT IGNORE INTO user_table(username, user_email, user_enabled, user_password, user_fname, user_lname)
 VALUES ('admin', 'webadmin@hdss.com', true , '$2a$10$SLlNbnvkIqatweZxewyZUeF6yrGexjppQpJgntGXCxWMQCaT3ORdi' , 'Administrator', 'System');

INSERT IGNORE INTO user_table(username, user_email, user_enabled, user_password, user_fname, user_lname)
 VALUES ('data', 'data@hdss.com', true , '$2a$10$SLlNbnvkIqatweZxewyZUeF6yrGexjppQpJgntGXCxWMQCaT3ORdi' , 'Data', 'Synchronization'); 

-- User : admin
-- Pwd: admin

-- User: data
-- pw: admin

	INSERT IGNORE INTO group_table(group_role, group_desc) values('ROLE_CONTROLLER', 'Systems Administrator');
  INSERT IGNORE INTO group_table(group_role, group_desc) values('ROLE_COORDINATOR', 'Coordinator');
  INSERT IGNORE INTO group_table(group_role, group_desc) values('ROLE_MANAGER', 'Data Manager');
  INSERT IGNORE INTO group_table(group_role, group_desc) values('ROLE_VIEWER', 'Viewer');


 INSERT IGNORE INTO user_group(username, group_role) values('admin', 'ROLE_CONTROLLER');
 INSERT IGNORE INTO user_group(username, group_role) values('data', 'ROLE_VIEWER');



ALTER TABLE visit ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE death ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE individual ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE inmigration ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE outmigration ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE pregnancyobservation ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE residency ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE location ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE relationship ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE socialgroup ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE sociodemographic ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE pregnancyoutcome ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE demographic ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE listing ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE vaccination ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE duplicate ADD COLUMN submitDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP;


-- fieldworker
INSERT IGNORE INTO fieldworker (fw_uuid, username, firstName, lastName, password, status,insertDate) 
VALUES ('UnknownFieldWorker','UNK', 'Unknown', 'FieldWorker', 'invalid-password-hash', 0,'2023-05-12 15:07:43');

-- individual
INSERT IGNORE INTO `individual`(uuid,extId,firstName,otherName,lastName,gender,dob,mother_uuid,father_uuid,insertDate,fw_uuid,dobAspect) 
VALUES('UNK','UNK','UNK',NULL,'UNK',1, '1800-12-19 15:07:43', 'UNK', 'UNK','2023-05-12 15:07:43','UnknownFieldWorker',1);
-- locationhierarchy
INSERT IGNORE INTO locationhierarchy(uuid,name,extId,level_uuid,parent_uuid) VALUES('hierarchy_root','', 'HIERARCHY_ROOT', NULL,NULL);


INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('294.00 bytes', 'individuals', '2023-05-19 11:32:55', 1, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('140.00 bytes', 'locations', '2023-05-19 11:32:57', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('142.00 bytes', 'residency', '2023-05-19 11:32:59', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('146.00 bytes', 'socialgroup', '2023-05-19 11:33:00', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('148.00 bytes', 'relationship', '2023-05-19 11:33:01', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('142.00 bytes', 'pregnancy', '2023-05-19 11:33:02', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('148.00 bytes', 'demographics', '2023-05-19 11:33:04', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('130.00 bytes', 'ses', '2023-05-19 11:33:05', 0, 'application/octet-stream');
INSERT IGNORE INTO task (`data`, `fileName`, `timestamp`, `total`, `type`) VALUES ('146.00 bytes', 'vaccination', '2023-05-19 11:33:05', 0, 'application/octet-stream');


-- KEYS

-- Inmigration
alter table inmigration add index FKD6922049851505F6 (residency_uuid), add constraint FKD6922049851505F6 foreign key (residency_uuid) references residency (uuid);

-- Outmigration
alter table outmigration add index FKE109DC40851505F6 (residency_uuid), add constraint FKE109DC40851505F6 foreign key (residency_uuid) references residency (uuid);
-- Profile
alter table sociodemographic add index FKFD3DA29930076DBC (socialgroup_uuid), add constraint FKFD3DA29930076DBC foreign key (socialgroup_uuid) references socialgroup (uuid);
-- Death
alter table death add index FK5B0927480470E9E (individual_uuid), add constraint FK5B0927480470E9E foreign key (individual_uuid) references individual (uuid);
alter table demographic add index FK5B0927480470E9C (individual_uuid), add constraint FK5B0927480470E9C foreign key (individual_uuid) references individual (uuid);


-- Outcome
alter table outcome add index FKBE0C0752948ED5FB (childuuid), add constraint FKBE0C0752948ED5FB foreign key (childuuid) references individual (uuid);

-- Listing
alter table listing add index FKD6922049851605F6 (location_uuid), add constraint FKD6922049851605F6 foreign key (location_uuid) references location (uuid);
alter table listing ADD INDEX FK6B05D4BEC630DBE (compno);

-- visit
alter table visit add index FKBE0C0752948ED5FV (socialgroup_uuid), add constraint FKBE0C0752948ED5FV foreign key (socialgroup_uuid) references socialgroup (uuid);

-- Pregnancy Outcome
alter table pregnancyoutcome add index FKBE0C0752948ED6FB (pregnancy_uuid), add constraint FKBE0C0752948ED6FB foreign key (pregnancy_uuid) references pregnancyobservation (uuid);


alter table vaccination add index FKD6922049851605FV (individual_uuid), add constraint FKD6922049851605FV foreign key (individual_uuid) references individual (uuid);
alter table individual ADD UNIQUE INDEX FK6B04D4BEC630DB8 (uuid);
alter table duplicate ADD INDEX FK6B04D4BEC630DBD (individual_uuid);
alter table duplicate ADD INDEX FK6B04D4BEC630DBE (dup_uuid);
alter table duplicate ADD INDEX FK6B04D4BEC630DBF (dup1_uuid);
alter table duplicate ADD INDEX FK6B04D4BEC630DBG (dup2_uuid);


INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '1', 'Doctor');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '2', 'Nurse/Midwife');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '3', 'TBA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '4', 'Relative/Friend');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '5', 'No One');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('assist', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '5', 'At home');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '1', 'Hospital');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '4', 'Traditional Birth Attendant\'s Home');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '2', 'Health Center/Clinic');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '9', 'On the way to clinic/hosptal');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '3', 'Private maternity home');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('birthPlace', '7', 'CHPS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '1', 'Within this community or village');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '2', 'From another community or village within the HDSS area');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '3', 'From another community within the Region (Bono East) but not in the HDSS area');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '4', 'Within Ghana but outside the region (Bono East)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '5', 'Africa');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '6', 'Europe');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '7', 'North America');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '8', 'South America');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '9', 'Asia');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('comingfrom', '10', 'Australia');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('complete', '1', 'Yes');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('complete', '2', 'No');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('COOKING_LOC_FCORRES', '1', 'In a separate building');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('COOKING_LOC_FCORRES', '2', 'Fully outdoors (no structure)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('COOKING_LOC_FCORRES', '3', 'Semi-enclosed outdoor structure');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '1', 'Malaria');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '2', 'HIV/AIDS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '3', 'TB');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '4', 'Other viral/bacterial infection');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '5', 'Accident');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '6', 'Crime');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '7', 'Age');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '8', 'Unknown');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathCause', '10', 'Disease, Illness');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '1', 'HOME');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '2', 'HOSPITAL');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '3', 'HEALTH CENTER');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '4', 'TRADITIONAL HEALER');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '5', 'PRIVATE MATERNITY HOME');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '6', 'ON ROUTE TO HEALTH FACILITY');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('deathPlace', '77', 'OTHER');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '1', 'None');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '6', 'Creche');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '2', 'Primary');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '3', 'JHS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '4', 'secondary');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('education', '5', 'Tertiary');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('endType', '3', 'Death');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('endType', '1', 'Active');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('endType', '2', 'Outmigration');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '8', 'No walls');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '9', 'Cane/palm/trunks');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '10', 'Dirt/mud');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '11', 'Dung');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '12', 'Straw/grass/sod');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '13', 'Bamboo with mud');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '14', 'Stone with mud');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '15', 'Uncovered adobe- clay bricks dried in the sun');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '16', 'Covered adobe - clay bricks dried in the sun with protective covering (i.e. thin layer of cement)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '17', 'Plywood');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '18', 'Cardboard');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '19', 'Reused wood');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '20', 'Cement');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '21', 'Stone with lime/cement');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '22', 'Bricks');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '23', 'Cement bricks');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '24', 'Wood planks/shingles');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('EXT_WALL_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '1', 'Food insecurity');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '2', 'Adequate rains during raining season');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '3', 'The soil in this area is rich in soil nutrients');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '4', 'Availability of market for farm produce');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '5', 'Due to crop failure or persistence crop failure in my previous place');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '6', 'Because of better land tenure system (Abunu, Abusa) ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '7', 'Due to availability of farm lands');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '8', 'Due to family inheritance or family business');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '9', 'Farm destroyed by Herdsmen often (Grazing of cattle)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '10', 'To generate income');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '11', 'Availability of land for Animal Grazing');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('farm', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '1', 'Earth/sand');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '2', 'Dung');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '3', 'Wood planks');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '4', 'Palm/bamboo');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '5', 'Parquet or polished wood');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '6', 'Vinyl or asphalt strips');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '7', 'Ceramic tiles');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '8', 'Cement/concrete');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '9', 'Carpet');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FLOOR_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('food', '1', 'Food items mainly for home consumption');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('food', '2', 'Food items mainly for sale on market');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('food', '3', 'Food items mainly for home consumption and sale on market');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FRQ', '1', 'Daily');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FRQ', '2', 'Weekly');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FRQ', '3', 'Monthly');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FRQ', '4', 'Less than once a month');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('FRQ', '5', 'Never (only smoke outside)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('gender', '1', 'Male');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('gender', '2', 'Female');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('groupType', '1', 'Family');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('groupType', '2', 'Cohort');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('grow', '1', 'Cash crops: mango, cashew, cocoa, ginger, tobacco, etc.');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '1', 'Piped water into dwelling');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '2', 'Piped to yard/plot');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '3', 'Public tap/standpipe');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '4', 'Tube well or borehole');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '5', 'Protected well');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '6', 'Unprotected well');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '7', 'Water from spring (protected)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '8', 'Water from spring (unprotected) ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '9', 'Tanker truck');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '10', 'Cart with small tank');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '11', 'Rainwater');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '12', 'Surface water (river/dam/lake/pond/stream/canal/irrigation channel)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '13', 'Bottled water or sachets');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '14', 'Water vendor (tap)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('H2O_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('HEAD_HH_FCORRES', '1', 'Pregnant woman');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('HEAD_HH_FCORRES', '2', 'Husband/partner of pregnant woman');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('HEAD_HH_FCORRES', '3', 'Mother/mother in-law of pregnant woman');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('HEAD_HH_FCORRES', '4', 'Father/father in-law of pregnant woman');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('HEAD_HH_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('howdel', '1', 'Normal/Spontaneous');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('howdel', '2', 'Caesarian Section');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('howdel', '3', 'Forceps');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('howdel', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '1', 'KINTAMPO HOSPITAL KINTAMPO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '2', 'ADOM MAT. HOME JEMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '3', 'JEMA HOSPITAL, JEMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '4', 'ANYIMA HEALTH CENTRE, ANYIMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '5', 'AMOMA HEALTH CENTRE, AMOMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '6', 'NEW LONGORO, HEALTH CENTRE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '7', 'DAWADAWA, HEALTH CENTRE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '8', 'PERPERTUAL MAT. HOME APESIKA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '9', 'KUNSU HEALTH CENTRE, KUNSU');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '10', 'EBENEZER MAT. HOME KINTAMPO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '11', 'ARMS MAT. HOME AJINA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '12', 'BUIPE HEALTH CENTRE, BUIPE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '13', 'BUSUAMA HEALTH CENTRE, BUSUAMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '14', 'ANNOA ASARE MEMORIAL CLINIC');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '15', 'PRINCE OF PEACE MATERNITY CLINIC');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '16', 'KADELSO HEALTH CENTRE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '17', 'GULUMPE HEALTH CENTRE(POLYCLINIC)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '18', 'MANSIE HEALTH CENTRE, MANSIE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '19', 'SUNKWA CLINIC KINTAMPO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '20', 'HOLY FAMILTY HOSPITAL, TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '21', 'ARMS MAT. HOME TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '22', 'AHAMADIYA HOSPITAL TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '23', 'BLUE CROSS CLINIC,TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '24', 'STATION CLINIC, TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '25', 'OPOKU AGYEMANG HOSPITAL, TECHIMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '26', 'FORIKROM HEALTH CENTRE, FORIKROM');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '27', 'BOURYEM HEALTH CENTRE, BOURYEM');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '28', 'OFFUMAN HEALTH CENTRE, OFFUMAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '29', 'AYORYA CHIPS COMPOUND');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '30', 'CHIPS COMPOUND, KAWAMPE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '31', 'CHIPS COMPOUND, PORTOR');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '32', 'CHIPS COMPOUND, ATTA AKURA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '33', 'CHIPS COMPOUND, BABATOR');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '34', 'CHIPS COMPOUND, ASANTEKWAA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '35', 'CHIPS COMPOUND, DWERE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '36', 'CHIPS COMPOUND, SABULE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '37', 'CHIPS COMPOUND, BANIANTWE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '38', 'CHIPS COMPOUND, AMPOMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '39', 'CHIPS COMPOUND, NTANKRO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '40', 'TUPBODOM, HEALTH CENTRE, TUOBODOM');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '41', 'AWOROWA HEALTH CENTRE, AWOROWA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '42', 'TANOSO HEALTH CENTRE, TANOSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '43', 'WENCHI HOSPITAL, WENCHI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '44', 'EBENEZER MAT. HOME, WENCHI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '45', 'EMIL MEMORIAL HOSPITAL, WENCHI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '46', 'NSAWKAW, HEALTH CENTRE, NSAWKAW');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '47', 'BADU HEALTH CENTRE, BADU');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '48', 'ST. JOSEPH’S HEALTH CENTRE, KOASE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '49', 'NCHIRAA HEALTH CENTRE, NCHIRAA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '50', 'SUBINSO HEALTH CENTRE, SUBINSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '51', 'MENJI HEALTH CENTRE, MENJI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '52', 'HOLY FAMILY, BEREKUM');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '53', 'BANDA-AHENKRO CLINIC');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '54', 'SAMPA HOSPITAL');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '55', 'DEBIBI HEALTH CENTRE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '56', 'SEIKWA HEALTH CLINIC');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '57', 'NYAASE CLINIC, NYAASE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '58', 'CHIPS COMPOUND, KWABIA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '59', 'CHIPS COMPOUND, KRABONSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '60', 'ST. THERESA’S HOSPITAL, NKORANZA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '61', 'NKORANZA HEALTH CENTRE, NKORANZA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '62', 'BONSU HEALTH CENTRE, BONSU');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '63', 'NKWABENG HEALTH CENTRE, NKWABEN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '64', 'YEFRI HEALTH CENTRE, YEFRI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '65', 'AKUMA HEALTH CENTRE, AKUMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '66', 'KRANKA HEALTH CENTRE, NKRANKA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '67', 'DROMANKESE, HEALTH CENTRE, DROMANKESE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '68', 'BUSUNYA HEALTH CENTRE, BUSUNYA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '69', 'CHIPS COMPOUND, DUMSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '70', 'CHIPS COMPOUND, PANINAMISA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '71', 'HOSPITAL YEZURA , KINTAMPO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '72', 'SUNYANI REGIONAL HOSPITAL, SUNYANI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '73', 'CHIPS COMPOUND, MIAWANI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '74', 'CHIPS COMPOUND, NANTE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '75', 'BAMBOI HEALTH CENTRE, BAMBOI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '76', 'NOT KNOWN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '77', 'HOSPITAL YEZURA, BUIPE(HOLISTIC MEDICARE)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '78', 'CLINIC ANNOR ASARE, BUIPE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '79', 'CLINIC INTEGRATED DEVPT. , KINTAMPO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '80', 'CHIPS COMPOUND, PRAMPOSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '81', 'CHIPS COMPOUND, KURAWURAKURA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '82', 'CHIPS COMPOUND, KOKUMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '83', 'CHIPS COMPOUND, BADU AKURA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '84', 'CHIPS COMPOUND, JATO AKURA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '85', 'CHIPS COMPOUND, NTAREBAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '86', 'HOME');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '87', 'CHIPS COMPOUND, MANSRA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '101', 'HEALTH CENTRE APESIKA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '89', 'CHIPS COMPOUND DROMANKUMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '90', 'CHIPS COMPOUND BOMINI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '91', 'CHIPS COMPOUND FIEMA');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '92', 'CHIPS COMPOUND BONTE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '93', 'CHIPS COMPOUND BODOM');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '94', 'CHIPS COMPOUND, MANSO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '95', 'CHIPS COMPOUND ASEKYE');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '96', 'CHIPS COMPOUND ASUEYI');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '97', 'CHIPS COMPOUND MESIDAN');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '98', 'CHIPS COMPOUND KROBO');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('INF_OHOLOC', '100', 'CHIPS COMPOUND AYEASU');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '1', 'Salaried worker (e.g., teacher, nurse, office)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '2', 'Small business');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '3', 'Business owner');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '4', 'Skilled labor');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '5', 'Unskilled labor');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '6', 'Subsistence farming');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '7', 'Commercial farming');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '8', 'fishing');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '9', 'Housewife');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '10', 'Not applicable/Not working');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('JOB', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('live', '1', 'Livestock mainly for home consumption');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('live', '2', 'Livestock mainly for sale on market');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('locationType', '1', 'Rural');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('locationType', '2', 'Urban');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '1', 'Married');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '2', 'Widowed');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '3', 'Single');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '4', 'Divorced');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '5', 'Separated');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '6', 'Cohabitation');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('marital', '7', 'Child/Minor');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MARITAL_SCORRES', '1', 'Married');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MARITAL_SCORRES', '2', 'Not married but living with partner (cohabitating)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MARITAL_SCORRES', '3', 'Divorced or permanently separated');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MARITAL_SCORRES', '4', 'Widowed');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MARITAL_SCORRES', '5', 'Single, never married');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('migType', '1', 'External Inmigration');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('migType', '2', 'Internal Inmigration');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MOBILE_ACCESS_FCORRES', '1', 'Yes- I have my own mobile phone');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MOBILE_ACCESS_FCORRES', '2', 'Yes, but I share the mobile phone with other people');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('MOBILE_ACCESS_FCORRES', '3', 'No, I do not have access to a mobile phone');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '1', 'Not necessary');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '2', 'Not customary');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '3', 'Lack of money');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '4', 'Too far');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '5', 'Transport problem');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '6', 'No one to accompany');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '7', 'Good services not available');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '8', 'Not permitted by family');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '9', 'Better service at home');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '10', 'No female doctor available');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '11', 'Inconvenient service hour');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '12', 'Afraid to go');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '13', 'Long waiting time');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '14', 'Religious Reasons');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('notdel', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '1', 'Farmer');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '2', 'Employed farmer');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '3', 'Merchant');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '4', 'Apprentiship');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '5', 'Private employee');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '6', 'Petty trade');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '7', 'Housewife ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '8', 'Student ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '9', 'Unemployed ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '10', 'Retired ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '11', 'Government Employee ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '12', 'NGO Worker ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '13', 'Daily Laborer ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '14', 'Self Employed ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '15', 'Child/Minor');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '16', 'Religious leader');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('occupation', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('outcometype', '1', 'Live Birth');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('outcometype', '2', 'Still Birth');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('outcometype', '3', 'Miscarriage');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('outcometype', '4', 'Abortion');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '1', 'Sole Ownership');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '2', 'Joint Ownership');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '3', 'Family/relation’s house');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '4', 'House provided rent free');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '5', 'Renting');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '6', 'Perching');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('OWN_RENT_SCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '1', 'Participant');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '2', 'Husband/partner');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '3', 'Participant and husband/partner jointly');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '4', 'Mother-in-law');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '5', 'Father-in-law');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('PD_DM_SCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '1', 'Due to family separation (Including Divorce)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '2', 'Due to health conditions');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '3', 'Due to marriage');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '4', 'I lost my job and income ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '5', 'Due to retirement');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '6', 'To learn a trade or apprentiship');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '7', 'Moved to own house');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '8', 'Due to Work or transfer by my organization (employer)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '9', 'Farming');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '10', 'Business/Trade');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '11', 'Returned after completion of education ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '12', 'Due to climate change (such as changes in temperature, rainfall pattern, increasing levels of greenhouse gases etc)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '13', 'Natural disaster (such as Famine, drought, flooding etc) ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '14', 'Due to political unrest or instability (communal, tribal or religious conflict) ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '15', 'New House');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '16', 'Came with/to relative(s)/parents');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '17', 'Came with spouse');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '18', 'Education/School');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '19', 'MISSEDOUT');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '20', 'Death of benefactor/Guardian');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('reason', '77', 'Other');
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to family separation (Including Divorce)', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to health conditions', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to marriage', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Lost job and income ', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to retirement', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'To learn a trade or apprentiship', 6);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Moved to own house', 7);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to Work or transfer by my organization (employer)', 8);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Farming', 9);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Business/Trade', 10);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Returned after completion of education ', 11);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to climate change (such as changes in temperature, rainfall pattern, increasing levels of greenhouse gases etc)', 12);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Natural disaster (such as Famine, drought, flooding etc) ', 13);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Due to political unrest or instability (communal, tribal or religious conflict) ', 14);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'New House', 15);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Went with/to relative(s)/parents', 16);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Went with spouse', 17);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Education/School', 18);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Not Known', 66);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Death of benefactor/Guardian', 20);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reasonForOutMigration', 'Other', 77);
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relationshipType', '2', 'Married');
-- INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relationshipType', '3', 'Separated/Divorced');
-- INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relationshipType', '4', 'Widowed');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relationshipType', '5', 'Living Together');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relendType', '1', 'Active');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relendType', '4', 'Dead');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relendType', '2', 'Widowed');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('relendType', '3', 'Divorced');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '1', 'Christian');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '2', 'Muslim');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '3', 'Traditional');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '4', 'Hindu');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '5', 'Buddhism');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '6', 'Judaism');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '7', 'Zoroastrianism');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '8', 'Shintoism');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '9', 'Sikhism');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '10', 'Atheist');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('religion', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '1', 'Head of Household');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '2', 'Spouse');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '3', 'Son/Daughter');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '4', 'Brother/Sister');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '5', 'Parent');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '6', 'Grandchild');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '7', 'Not Related');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '8', 'Other Relative');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('rltnhead', '9', 'Don\'t Know');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '1', 'No roof');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '2', 'Thatch/palm leaf');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '3', 'Sod/grass');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '4', 'Rustic mat');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '5', 'Cardboard');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '6', 'Palm/bamboo');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '7', 'Wood planks (rudimentary roofing)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '8', 'Wood (finished roofing)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '9', 'Metal (e.g. iron, tin sheets');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '10', 'Calamine/cement fiber');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '11', 'Ceramic tiles');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '12', 'Cement');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '13', 'Roofing shingles');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('ROOF_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('shortlong', '1', 'Long (more than 1 year)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('shortlong', '2', 'Short (up to a year)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('shortlong', '3', 'Unknown');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('site', '1', 'KHDSS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('site', '2', 'NHDSS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('site', '3', 'DHDSS');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('size', '1', 'Very small');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('size', '2', 'Small');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('size', '3', 'Average');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('size', '4', 'Large');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('size', '5', 'Larger than usual');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('startType', '3', 'Enumeration');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('startType', '1', 'Inmigration');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('startType', '2', 'Birth');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '1', 'Active');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '2', 'Commercial');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '3', 'Could not locate');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '4', 'Deserted/Broken');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '5', 'Incomplete');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '6', 'Unoccupied');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('status', '7', 'Not Known');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '1', 'Electric stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '2', 'Solar cooker');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '3', 'Liquified petroleum gas/cooking gas stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '4', 'Piped natural gas stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '5', 'Biogas stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '6', 'Liquid fuel stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '7', 'Manufactured solid fuel stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '8', 'Traditional solid fuel stove');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '9', 'Three stone stove/open fire');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '10', 'No food cooked in household');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('STOVE_FCORRES', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('submit', '1', 'Yes');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('submit', '2', 'No');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '1', 'Flush/pour flush to piped sewer system');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '2', 'Flush/pour flush to septic tank');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '3', 'Flush/pour flush to pit latrine');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '4', 'Flush/pour flush to somewhere else');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '5', 'Flush/pour flush, don’t know where');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '6', 'Ventilated improved pit latrine');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '7', 'Pit latrine with slab');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '8', 'Pit latrine without slab/open pit');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '9', 'Composting toilet');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '10', 'Bucket toilet');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '11', 'Hanging toilet/hanging latrine');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '12', 'No facility/bush/field');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_FCORRES', '77', 'Other ');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_LOC_FCORRES', '1', 'Within the household structure');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_LOC_FCORRES', '2', 'Neighbor\'s home/structure');
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('yn_anc', 'Yes', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('yn_anc', 'No', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('yn_anc', 'Yes (Card Not Available)', 3);
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_LOC_FCORRES', '3', 'Public toilet');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_LOC_FCORRES', '77', 'other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_SHARE_NUM_FCORRES', '1', 'Less than 5 households');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_SHARE_NUM_FCORRES', '2', '5-9 households');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('TOILET_SHARE_NUM_FCORRES', '3', '10 or more households (includes public toilet)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '1', 'Akan');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '2', 'Bimoba (Gruma)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '3', 'Chokosi');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '4', 'Dagarti');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '5', 'Frafra');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '6', 'Kusasi');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '7', 'Fulani');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '8', 'Ga');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '9', 'Ewe');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '10', 'Adangbe');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '11', 'Sisala');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '12', 'Wala');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '13', 'Gonja');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '14', 'Dagomba');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '15', 'Mamprusi/Tampruma');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '16', 'Konkomba');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '17', 'Basare');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '18', 'Mo');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '19', 'Zambraba');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '20', 'Banda');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '21', 'Pantra');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '22', 'Bawule');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '23', 'Dwula (wangara)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '24', 'Grushie (Kasina, Nankana)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '25', 'Bissa(Busanga)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '26', 'Chumburu');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '27', 'Kotokoli');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '28', 'Mossi');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '29', 'Yuroba');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '30', 'Igbo');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '31', 'Hausa');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '32', 'Kambara');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '33', 'Kanjaga/Builsa');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('tribe', '77', 'Other');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '1', 'Within this community or village');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '2', 'TO another community or village within the HDSS area');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '3', 'To another community within the Region (Bono East) but not in the HDSS area');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '4', 'Within Ghana but outside the region (Bono East)');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '5', 'Africa');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '6', 'Europe');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '7', 'North America');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '8', 'South America');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '9', 'Asia');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '10', 'Australia');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('whereoutside', '11', 'Not Known');
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Child Welfare clinic', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Bought it', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Received as a gift', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'ANC visit', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Received during mass campaign', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'From NGO', 6);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Borrowed', 7);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetSou', 'Other', 77);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetLoc', 'Still in use', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetLoc', 'Being used by other household members', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetLoc', 'Lend', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetLoc', 'Destroyed', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('bnetLoc', 'Other', 77);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('nhis', 'Yes, Active', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('nhis', 'Yes, expired', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('nhis', 'No', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('nhis', 'Card not seen', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HL', 'Immediate', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HL', 'Later same day', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HL', 'Day two(2)', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HL', 'Three or more days', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HL', 'Never', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('rea', 'Respiratory infection', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('rea', 'Fever', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('rea', 'Diarrhoea', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('rea', 'Accident', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('rea', 'Other', 77);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('onet', 'Always', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('onet', 'Sometimes', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('onet', 'Rainy season', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('onet', 'Dry season', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('onet', 'Never', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HC', 'Yes seen', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HC', 'Yes, not seen', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HC', 'No, never had a card', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HC', 'No, had card but lost it', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('HC', 'No information', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Was at health facility to get Vaccine but did not succeed', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Mother does not know of vaccination schedule', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Mother considers child too small/sick for vaccination', 3);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Religious/Cultural reasons', 4);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Distance to health facility', 5);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Received but not indicated on card', 6);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Other', 77);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('reavac', 'Not Applicable', 8);
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('scar', '1', 'Yes');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('scar', '2', 'No');
INSERT INTO codebook (codeFeature, codeValue, codeLabel) VALUES ('scar', '3', 'Child not available');
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('cashcrops', 'Cash crops: mango, cashew, cocoa, ginger, tobacco, etc.', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('livestock', 'Livestock mainly for home consumption', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('livestock', 'Livestock mainly for sale on market', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('livestock', 'Livestock mainly for home consumption and sale on market', 3);
INSERT INTO settings (`earliestDate`, `father_age`, `hoh_age`, `mother_age`, `rel_age`, `updates`, `enumeration`) VALUES ('2018-01-01', 12, 14, 12, 12,true,false);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('modules', 'HDSS', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('modules', 'Covid', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('enabled', 'True', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('enabled', 'False', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('odk_gender', 'Male', 1);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('odk_gender', 'Female', 2);
INSERT INTO codebook (codeFeature, codeLabel, codeValue) VALUES ('odk_gender', 'All', 3);

